name: Convert SCPT to APP and Release

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Convert .scpt to .app
        run: |
          mkdir -p output
          osacompile -o output/script.app script.scpt
          # 実行権限を付与
          chmod +x output/script.app/Contents/MacOS/*
          # 生成されたバンドル構造を確認
          ls -lR output/script.app

      - name: Archive .app as tar.gz
        run: |
          tar -czf output/script.tar.gz -C output script.app

      - name: Create Release and Upload .tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG_NAME="v$(date +%Y%m%d%H%M%S)"
          gh release create "$TAG_NAME" --title "Release $TAG_NAME" --notes "Converted .app file" --draft
          gh release upload "$TAG_NAME" output/script.tar.gz
