name: Convert SCPT to APP and Release

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Convert .scpt to .app
        run: |
          # 作業ディレクトリの内容を確認
          ls -la
          # script.scpt が存在するか確認
          if [ -f "script.scpt" ]; then
            echo "script.scpt found"
          else
            echo "Error: script.scpt not found" && exit 1
          fi
          mkdir -p output
          # osacompile の実行
          osacompile -o output/script.app script.scpt || { echo "osacompile failed"; exit 1; }
          # 実行権限を付与
          chmod +x output/script.app/Contents/MacOS/*
          # 生成された構造を確認
          ls -lR output/script.app

      - name: Archive .app as tar.gz
        run: |
          tar -czf output/script.tar.gz -C output script.app

      - name: Create Release and Upload .tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG_NAME="v$(date +%Y%m%d%H%M%S)"
          gh release create "$TAG_NAME" --title "Release $TAG_NAME" --notes "Converted .app file" --draft
          gh release upload "$TAG_NAME" output/script.tar.gz
